написала функцию рандомных чисел в заданном диапозоне
htmlacademy-javascript/1662371-keksobooking-22 pull request #3
Opened 2021-02-04 08:19 UTC by OrangeRaccoonAlex

2021-02-04 09:47 UTC, maxim-usikov requested changes

2021-02-04 09:47 UTC, maxim-usikov commented on js/main.js
> +getRandomInt(0, 20);
> Функция, возвращающая случайное целое число из переданного диапазона включительно

Эта функция работает для предела: `[min, max)` Включает минимальное число, не включает максимальное. А должно работать для: `[min, max]` включать и минимальное и максимальное.


Посмотри в сторону использования: Math.ceil, Math.floor и Math.random (подсказка на mdn есть решение для твоего случая `getRandomIntInclusive`, но оно не обрабатывает следующие кейсы.


> Учтите, что диапазон может быть только положительный, включая ноль. 
* min, max >= 0

> А также придумайте, как функция должна вести себя, если передать значение «до» меньшее, чем значение «от», или равное ему.

* if min < max делаем что?


Это что касается целых чисел.

> Учтите, что диапазон может быть только положительный, включая ноль. А также придумайте, как функция должна вести себя, если передать значение «до» меньшее, чем значение «от», или равное ему. Не забудьте, что в случае с дробными числами диапазон может быть в десятых, сотых, тысячных и т. д. долях. Например, 1.1, 1.2 — корректный диапазон.

Для числе с плавающей точкой нужно чуть переделать.


т.е. по итогу должна получиться функция которая на вход принимает 3 аргумента: min, max, fractionDigits и возвращать number

2021-02-04 16:59 UTC, OrangeRaccoonAlex commented on js/main.js
> +getRandomInt(0, 20);
сюда может входить такое поведение, что я, например, буду выводить ошибку что "задан не верный диапазон"? 
`А также придумайте, как функция должна вести себя, если передать значение «до» меньшее, чем значение «от», или равное ему.

`

2021-02-04 17:05 UTC, OrangeRaccoonAlex commented on js/main.js
> +getRandomInt(0, 20);
опытным путем я выяснила, что минимальный и максимальный диапазоны тоже включаются

> Эта функция работает для предела: [min, max) Включает минимальное число, не включает максимальное.

2021-02-04 17:55 UTC, maxim-usikov commented on js/main.js
> +getRandomInt(0, 20);
> сюда может входить такое поведение, что я, например, буду выводить ошибку что "задан не верный диапазон"? 
> 
> 
> 
> > А также придумайте, как функция должна вести себя, если передать значение «до» меньшее, чем значение «от», или равное ему.
> 
> > 

Может, тут смысл в придумайте

2021-02-06 06:50 UTC, maxim-usikov requested changes

2021-02-06 06:50 UTC, maxim-usikov commented on js/main.js
> +getRandomInt(0, 20, 100);
У тебя должно быть 2 функции одна просто генерирует случайное целое число в диапазоне [min, max], с условиями: min < max, (min || max) < 0 (придумать что делать, например: вывести ошибку, выкинуть исключение, вернуть null, свой вариант)

Вторая функция генерирует случайное число с плавающей точкой в диапазоне [min, max] в неё можно так же передать количество знаков после запятой, с теми же условиями: min < max, (min || max) < 0 (придумать что делать, например: вывести ошибку, выкинуть исключение, вернуть null, свой вариант)


Первая функция:

```js
getRandomInt(min, max) {
  // ...

  return intNumber;
}
```

Вторая функция:

```js
getRandomFloat(min, max, fractionDigits) {
  // ...

  return floatNumber;
}
```

2021-02-08 04:59 UTC, maxim-usikov approved these changes

2021-02-08 04:59 UTC, merged