Отрисуй меня полностью (часть 1)
htmlacademy-javascript/1662371-keksobooking-22 pull request #6
Opened 2021-02-26 13:35 UTC by OrangeRaccoonAlex

создала модуль создания разметки карточки объявления и модуль словаря

2021-02-26 20:02 UTC, maxim-usikov requested changes

2021-02-26 20:02 UTC, maxim-usikov commented on js/generatingPopupMarkup.js
> +let popupTitle = document.querySelector('.popup__title');
+ по идее у тебя должны быть функции:

```
renderCards(cardsData)
renderCard(cardData)
```

2021-02-27 12:53 UTC, OrangeRaccoonAlex commented on js/generatingPopupMarkup.js
> +let popupTitle = document.querySelector('.popup__title');
я правильно понимаю что по итогу у меня должно получиться все тоже самое, только обернутое в функцию с кучей внутренних проверок наличия данных?

я в #map-canvas и #card ничего не отрисовывала просто потому что не поняла, что от меня хотят. наличие данных проверяла заменив template на div.
я пока не вижу общую картину того, что будет в будущем, поэтому не совсем понимаю что от меня хотят в задании

2021-02-27 13:55 UTC, maxim-usikov commented on js/generatingPopupMarkup.js
> +let popupTitle = document.querySelector('.popup__title');
Поняла правильно, возможно станет понятнее во второй части. Пока давай все засунем в функцию

2021-02-27 18:10 UTC, OrangeRaccoonAlex commented on js/generatingPopupMarkup.js
> +for (let i = 0; i < createAd().offer.photos.length; i++) {
сколько не билась, не получается. что-то совсем у меня беда с фотографиями

2021-02-28 20:23 UTC, maxim-usikov approved these changes

2021-02-28 20:23 UTC, merged